# Demo app.
runtime: python27
api_version: 1
threadsafe: true

libraries:

- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:

# Main app.  All the real work is here.
- url: /.*
  script: main.APPLICATION
